### ISSUE TITLE
commentit didn't support Chinese

### ISSUE THREAD

**Issue by dbarobin** [guilro/commentit#1] opened 2015-10-25 04:05 UTC
Thanks for your great work!

When I added comment support via this plugin, and made a test. When compiled, error came out like this:

> The file `_posts/Other/2015-07-04-mbp.md/#excerpt` is not properly UTF-8 encoded. For more information, see https://help.github.com/articles/page-build-failed-file-is-not-properly-utf8-encoded.

I added `encoding: UTF-8` in my `_config.yml`, compiled again, but it didn't work yet.

That is to say, **commentit don't support Chinese.**

Here is my env:

> Ruby: 1.9.3
> Jekyll: 2.5.3
> Local OS: Mac OS X EI Capitan

Thanks again.

**Comment by guilro** [comment] 2015-10-25 13:56
Hello, thanks for your report.

What test did you make ? Could you provide a link to the commit which provoked this error ? There was no problem so far with Chinese (there are a lot of comments in Chinese on my blog), and Chinese character are converted to html entities before being written to the file, so I need to investigate a little more to understand the cause of the problem.

**Comment by dbarobin** [comment] 2015-10-26 02:06
Thanks for your reply.

Here is my testing flow:

* Add commentit plugin in my template file, see at: [[Enhance] Add comment support via Comm(ent|it)](https://github.com/dbarobin/dbarobin.github.io/commit/ea0c97fa0026dd17f5106b05dfd9280e2c399e65);

* Settings of commentit as following image:

![Settings](http://img2.ph.126.net/oPfBpsBUQjlC3bNLQbCyVg==/6630441044072765249.png)

* Make a comment at [MBP](http://dbarobin.com/2015/07/04/mbp/);

* Merge pull request from my comment;

* Git pull locally;

* Run `jekyll server` to build locally, then have a problem;

* Push to remote repo, build error again.

Due to this build error, I've deleted this wrong commit, so you can't see this anymore.

Thanks.

**Comment by kylegraycar** [comment] 2015-11-24 01:42
I too had a similar problem, and it also created a build error.
Here's the pull request from my test comment that I committed:
https://github.com/kylegraycar/kylegraycar.github.io/commit/a101b9e4ea98babb6a4d43c1bac661d008bfbc21

Interestingly, when I changed the characters back into Chinese myself, the website again builds like normal.

**Comment by guilro** [comment] 2015-11-24 08:49
Thanks for the report. I couldn't reproduce the bug first time (on my blog there are plenty of comments in Chinese).

It seems that the problem comes from Chinese in the page, not in comments themselves.

I cloned your repository and will investigate it tomorrow ;)

**Closed** 2015-11-25 00:00 UTC

**Comment by guilro** [comment] 2015-11-25 00:13
It shoud be good now !

@kylegraycar, I used the content from a post of your blog as data for the automated tests. This way I had a potentially buggy post without comment, plus the version you fixed manually as reference. If there is any problem with a copy of your content staying in commentit.io test suite, please tell me, and I will generate fake data myself. In any case, thanks a lot for the report !

**Comment by dbarobin** [comment] 2015-11-29 01:41
@guilro It works out. Thanks!

**Comment by yanhaijing** [comment] 2017-04-11 12:06
same need
